---
title: "Reproducible Research Assignment - Week 2"
author: "Chandrasekar Ganesan"
date: "February 26, 2017"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=TRUE, warning=FALSE, message=FALSE, eval=TRUE)
```

## Getting and processing the data

>Let's first get the data

```{r}
library(dplyr)
library(graphics)

activitydata <- read.csv("activity.csv", header = TRUE, na.strings = "NA")

#Format the date column as date
activitydata$date <- as.POSIXct(activitydata$date)

isdatana <- is.na(activitydata$steps)

#Ignore the NA values
data <- activitydata[!isdatana,]
```

## Histogram of the total number of steps taken each day

```{r}
steps_per_day_group <- group_by(data, date)
steps_per_day <- summarize(steps_per_day_group,sumsteps=sum(steps))
hist(steps_per_day$sumsteps, xlab="Sum of steps per day", ylab = "Frequency", main="Histogram of number of steps per day")

```

## Mean and Median steps taken each day
```{r}
summary(steps_per_day)

```

**Mean steps are 10766, Median steps are 10765**

## Average daily activity pattern

```{r}
steps_group <- aggregate(steps ~ interval, data, mean)

plot(steps_group$interval, steps_group$steps, type="l", xlab="Interval", ylab="Average steps", main="Average daily activity pattern")

```


## The 5-minute interval that, on average, contains the maximum number of steps

```{r}
steps_group <- aggregate(steps ~ interval, data, mean)

plot(steps_group$interval, steps_group$steps, type="l", xlab="Interval", ylab="Average steps", main="Average daily activity pattern")

abline(h = max(steps_group$steps), lty=2, col='red')

text(y=max(steps_group$steps)-5,x=400,labels = paste("Max Steps =",max(steps_group$steps),sep=" "))
```

## Imputing missing data


